#!/bin/sh
# program compile
#

#main
	Param=$1
	case "$Param" in
		c)			COMP_TARGET=$2; export COMP_TARGET
					make -f Makefile.c;;
		ucs)			COMP_TARGET=$2; export COMP_TARGET
					make -f Makefile.ucs;;
		sdl)			COMP_TARGET=$2; export COMP_TARGET
					make -f Makefile.sdl;;
		tbc)			COMP_TARGET=$2; export COMP_TARGET
					make -f Makefile.tbc all;;
		pc)			COMP_TARGET=$2; export COMP_TARGET
					make -f Makefile.pc all;;
		psdl)			COMP_TARGET=$2; export COMP_TARGET
					make -f Makefile.psdl all;;
		mr)			COMP_TARGET=$2; export COMP_TARGET
					make -f Makefile.mr all;;
		mr2)			COMP_TARGET=$2; export COMP_TARGET
					make -f Makefile.mr2 all;;
		mt)			  COMP_TARGET=$2; export COMP_TARGET
					make -f Makefile.mt;;					
		clean)			make -f Makefile.pc clean;;
		*)			echo "Usage: $0 argument";;
	esac
