/*
 * TMAX FDL header file. automatically generated by fdlc
 * Field Table File : bank.f
 */



#define MY_ID 	 ((FLDKEY)469762148) /* number: 100 type: string */ 
#define REC_ID 	 ((FLDKEY)469762149) /* number: 101 type: string */ 
#define AMOUNT 	 ((FLDKEY)201326694) /* number: 102 type: int */ 
#define MY_BANK 	 ((FLDKEY)469762151) /* number: 103 type: string */ 
#define REC_BANK 	 ((FLDKEY)469762152) /* number: 104 type: string */ 
#define MESSAGE 	 ((FLDKEY)469762154) /* number: 106 type: string */ 
